from abc import ABC, abstractmethod
import numpy as np

class BaseIndex(ABC):
    @abstractmethod
    def add(self, ids, vectors: np.ndarray): ...
    @abstractmethod
    def search(self, query: np.ndarray, k: int = 5): ...
    @abstractmethod
    def dim(self) -> int: ...
    @abstractmethod
    def get_ids(self): ...
    @abstractmethod
    def get_vectors(self) -> np.ndarray: ...
